apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-scanner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-scanner
  template:
    metadata:
      labels:
        app: security-scanner
    spec:
      serviceAccountName: security-scanner
      containers:
      - name: scanner
        image: k8s-security-scanner:latest
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: security-scanner
  namespace: default
spec:
  selector:
    app: security-scanner
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer